name: timely
description: "A new Flutter project."
publish_to: 'none'
version: 0.2.3+1

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  go_router:  
  intl:  
  provider:  
  timezone: ^0.9.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "asset/logo.jpg"
  
flutter:
  uses-material-design: true

  assets:
    - asset/
